"""empty message

Revision ID: 2c3bfa97f9a2
Revises: 472e89a00458
Create Date: 2023-02-06 13:05:18.381272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c3bfa97f9a2'
down_revision = '472e89a00458'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interfaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interfaces')
    # ### end Alembic commands ###
